---
- hosts: default
  connection: local
  become: yes
  
  tasks:
   - name: test connection
     ping:

   - name: add REMI repository 
     yum:
       name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
       state: present
       
   - name: enable remi-php72
     command: "yum-config-manager --enable remi-php72"
     
   - name: install packages
     yum:
       name: "{{item}}"
       state: present
     with_items:
       - mc
       - nano
       - iptables-services
       - yum-utils
       - nginx
       - httpd
       - php
       - php-mysql
       - php-gd
       - php-pecl-imagick
       - php-pecl-zip
       - php-xml
       - php-pecl-redis
       - mariadb
       - mariadb-server
       - unzip
       - redis

       
   - name: disable firewalld service on system start up
     systemd:
       name: firewalld
       enabled: no

   - name: stop firewalld service
     systemd:
       name: firewalld
       state: stopped

   - name: Download cs-cart
     get_url:
       url: http://helpdesk.cs-cart.com/index.php?dispatch=download.download&file_id=1402&ekey=4f454e863a36c05f8a41c1b42bea3b5c&msgid=15389917530000000975;0;0&x-email=gsaburov@list.ru&js=1
       dest: /var/www/html/cscart_v4.8.2.SP2.zip
       
   - name: Unarchive a file that is already on the remote machine
     unarchive:
       src: /var/www/html/cscart_v4.8.2.SP2.zip
       dest: /var/www/html/
       creates: /var/www/html/index.php       

   - name: copy configuration files
     copy:
       src: "{{item.src}}"
       dest: "{{item.dest}}"
       owner: root
       group: root
       mode: 0666
     with_items:
       - {src: 'files/iptables', dest: '/etc/sysconfig/iptables'}
       - {src: 'files/httpd.conf', dest: '/etc/httpd/conf/httpd.conf'}
       - {src: 'files/nginx.conf', dest: '/etc/nginx/nginx.conf'}
       - {src: 'files/nginx-proxy.conf', dest: '/etc/nginx/conf.d/default.conf'}
       - {src: 'files/config.local.php', dest: '/var/www/html/config.local.php'}
     notify:
       - restart services on config update
    
   - name: enable services on system start up
     systemd:
       name: "{{item}}"
       enabled: yes
     with_items:
       - iptables
       - ip6tables
       - httpd
       - mariadb
       - nginx
       - redis

   - name: start services
     systemd:
       name: "{{item}}"
       state: started
     with_items:
       - iptables
       - ip6tables
       - httpd
       - mariadb
       - nginx
       - redis
       
  handlers:
    - name: restart services on config update
      systemd:
        name: "{{item}}"
        state: restarted
      with_items:
        - iptables
        - ip6tables
        - httpd
        - nginx